/* AUTO-GENERATED FILE. DO NOT EDIT.
   * Generated by scripts/generate-policy-registry.mjs
   */
import { BaseNamePolicy } from "./policies/BaseNamePolicy";
import { CaseInsensitivePolicy } from "./policies/CaseInsensitivePolicy";
import { CaseSensitivePolicy } from "./policies/CaseSensitivePolicy";
import { ExternalServicePolicy } from "./policies/ExternalServicePolicy";
import { PrefixOverlapPolicy } from "./policies/PrefixOverlapPolicy";
import { SameFilePolicy } from "./policies/SameFilePolicy";
import { UniqueFilesPolicy } from "./policies/UniqueFilesPolicy";
import { WordFormPolicy } from "./policies/WordFormPolicy";
import { _registerPolicy } from "./registry";

// Instantiate and register each discovered policy
_registerPolicy("base-name", new BaseNamePolicy());
_registerPolicy("case-insensitive", new CaseInsensitivePolicy());
_registerPolicy("case-sensitive", new CaseSensitivePolicy());
// _registerPolicy("external-service", new ExternalServicePolicy({ endpoint: "http://localhost:8787/snw/key", apiKey: "env:SNW_KEY" })); // TODO: Configure external service policy
_registerPolicy("prefix-overlap", new PrefixOverlapPolicy());
_registerPolicy("same-file", new SameFilePolicy());
_registerPolicy("unique-files", new UniqueFilesPolicy());
_registerPolicy("word-form", new WordFormPolicy());
