/* AUTO-GENERATED FILE. DO NOT EDIT.
   * Generated by scripts/generate-policy-registry.mjs
   */

export type WikilinkEquivalencePolicyType = "base-name" | "case-insensitive" | "case-sensitive" | "external-service" | "prefix-overlap" | "same-file" | "unique-files" | "word-form";
